
# Copyright (c) 2025 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
 
spring.application.name=bankMex
server.port=8083
logging.level.org.springframework=INFO
management.endpoints.web.exposure.include=mappings

spring.jersey.type= filter

maxStatusWait = 60000
cacheSize = 100000
finalize = true

osaga.bankb.conn.type=${OSAGA_BANKB_CONN_TYPE}
osaga.bankb.tns.admin=${OSAGA_BANKB_TNS_ADMIN}
osaga.bankb.tns.alias=${OSAGA_BANKB_TNS_ALIAS}
osaga.bankb.host=${OSAGA_BANKB_HOST}
osaga.bankb.port=${OSAGA_BANKB_PORT}
osaga.bankb.serviceName=${OSAGA_BANKB_SERVICENAME}
osaga.bankb.username=${OSAGA_BANKB_USERNAME}
osaga.bankb.password=${OSAGA_BANKB_PASSWORD}
osaga.bankb.numListeners=1
osaga.bankb.numPublishers=0
osaga.bankb.maxpool=10
osaga.bankb.initialPoolSize=2


# Zipkin Tracing Configuration
tracing.zipkin.url=${ZIPKIN_URL_EXTENDED}
tracing.service.version=1.0.0
tracing.enabled=${ENABLE_ZIPKIN}
