
# Copyright (c) 2025 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
 

spring.application.name=bankChicago
server.port=8082
logging.level.org.springframework=INFO
management.endpoints.web.exposure.include=mappings

spring.jersey.type= filter

maxStatusWait = 60000
cacheSize = 100000
finalize = true

osaga.banka.conn.type=${OSAGA_BANKA_CONN_TYPE}
osaga.banka.tns.admin=${OSAGA_BANKA_TNS_ADMIN}
osaga.banka.tns.alias=${OSAGA_BANKA_TNS_ALIAS}
osaga.banka.host=${OSAGA_BANKA_HOST}
osaga.banka.port=${OSAGA_BANKA_PORT}
osaga.banka.serviceName=${OSAGA_BANKA_SERVICENAME}
osaga.banka.username=${OSAGA_BANKA_USERNAME}
osaga.banka.password=${OSAGA_BANKA_PASSWORD}
osaga.banka.numListeners=1
osaga.banka.numPublishers=0
osaga.banka.maxpool=5
osaga.banka.initialPoolSize=2

# Zipkin Tracing Configuration
tracing.zipkin.url=${ZIPKIN_URL_EXTENDED}
tracing.service.version=1.0.0
tracing.enabled=${ENABLE_ZIPKIN}
