# Copyright (c) 2025 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# application.properties
spring.application.name=orchestrator
server.port=8081
logging.level.org.springframework=INFO
management.endpoints.web.exposure.include=mappings

spring.jersey.type=filter

# Zipkin Tracing Configuration
tracing.zipkin.url=${ZIPKIN_URL_EXTENDED}
tracing.service.version=1.0.0
tracing.enabled=${ENABLE_ZIPKIN}

maxStatusWait=60000
cacheSize=100000
finalize=true

osaga.cloudbank.conn.type=${OSAGA_CLOUDBANK_CONN_TYPE}
osaga.cloudbank.tns.admin=${OSAGA_CLOUDBANK_TNS_ADMIN}
osaga.cloudbank.tns.alias=${OSAGA_CLOUDBANK_TNS_ALIAS}
osaga.cloudbank.host=${OSAGA_CLOUDBANK_HOST}
osaga.cloudbank.port=${OSAGA_CLOUDBANK_PORT}
osaga.cloudbank.serviceName=${OSAGA_CLOUDBANK_SERVICENAME}
osaga.cloudbank.username=${OSAGA_CLOUDBANK_USERNAME}
osaga.cloudbank.password=${OSAGA_CLOUDBANK_PASSWORD}
osaga.cloudbank.numListeners=1
osaga.cloudbank.numPublishers=1
osaga.cloudbank.maxpool=10
osaga.cloudbank.initialPoolSize=2

URL_VIEW_ALL_ACCOUNTS_BANK_A=http://bankA:8082/banka/viewAccounts
URL_VERIFY_ACCOUNT_BANK_A=http://bankA:8082/banka/isInBank
URL_VIEW_ALL_ACCOUNTS_BANK_B=http://bankB:8083/bankb/viewAccounts
